version:     "0020b--12-Sep-2021"
copyright:   "2021-2021"
description:
  Hello world!
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "MyLog"
  link:      "/TXT/mylog.txt/
- navbar:    "TarBall"
  link:      "/template.tar.bz2"
- navbar:    "GitHub"
  link:      "https://github.com/figoathallah/"
title:       "figoathallah's Github Page"
lang:        "en-US"
author:      "Figo Athallah"
address:     "Cilandak"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "pikari"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


